# Generated by Django 3.0.8 on 2020-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client_token',
            field=models.CharField(default='nlxicWe2bsAPXn2Cxpezg3JYNsnVyGobnQ47SZJFiV3eeXL7Gv', max_length=52),
        ),
    ]
