# Generated by Django 3.0.8 on 2020-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200728_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_uploads/avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_rating',
            field=models.CharField(choices=[(None, '(No Data Avaiable from any source)'), (1, 'Required to pay a fee or deposit'), (2, 'Subprime borrower, require higher down payment'), (3, 'Offer unfavorable terms (i.e. low down-payment)'), (4, 'Offer favorable terms on credit accounts'), (5, 'Top of the list offer the best rates')], default='(No Data Avaiable from any source)', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client_token',
            field=models.CharField(default='bZKcOnv8oQKAsSbE1kc86Nt4Sgr2gGz8eHGV25nqQJ950bRy3O', max_length=52),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_uploads/profile_pictures/'),
        ),
    ]
