# Generated by Django 3.0.8 on 2020-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200730_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client_token',
            field=models.CharField(default='WM7SnK1wjqxdXb6aLJbAaSJuNcixnlA2QJrCOdppKaisKadL2u', max_length=52),
        ),
    ]
