# Generated by Django 3.0.8 on 2020-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200730_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client_token',
            field=models.CharField(default='xFGsEbgNwrzFitfd8J6NFTHFOpqFu6Jd6aK2J5YhqWeda1eFgN', max_length=52),
        ),
    ]
