# Generated by Django 3.1 on 2020-08-16 23:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_delivery', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('mobile_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('[0-9]{3}[-]{1}[0-9]{3}[-]{1}[0-9]{4}')])),
                ('is_active_customer', models.BooleanField(default=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='users_profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
