[package]
	name = "hello-rust"
	version = "0.1.0"
	authors = [
		"wearypossum4770 <wearypossum4770@yahoo.com>",
		
		]
	edition = "2018"
	autobins = false
	autoexamples = false
	autotests = false
	autobenches = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
	celery = "0.3.1"
	amq-protocol = "5.1.0"
	time = "0.1.12"
	regex = "0.1.41"
#[lib]
#	name = "foo"           # The name of the target.
#	path = "src/lib.rs"    # The source file of the target.
#	test = true            # Is tested by default.
#	doctest = true         # Documentation examples are tested by default.
	bench = true           # Is benchmarked by default.
#	doc = true             # Is documented by default.
	plugin = false         # Used as a compiler plugin (deprecated).
	proc-macro = false     # Set to `true` for a proc-macro library.
	harness = true         # Use libtest harness.
	edition = "2015"       # The edition of the target.
	crate-type = ["lib"]   # The crate types to generate.
	required-features = [] # Features required to build this target (N/A for lib).
[features]
	# ...
	postgres = []
	sqlite = []
	tools = []

[[bin]]
	name = "my-pg-tool"
	required-features = ["postgres", "tools"]
