abbreviations = [

 	["Admission", "Admis."],
 	["Affidavit", "Aff."],
 	["Affirm","Affirm"],
 	["Amended","Am."],
 	["Answer", "Answer"],
 	["Appeal","Appeal"],
 	["Appellant", "Appellant"],
 	["Appellee", "Appellee"],
 	["Appendix", "App."],
 	["Application","Appl."],
 	["Argument","Arg."],
 	["Attachment", "Attach."],
 	["Attorney", "Att’y"],
 	["Brief", "Br."],
 	["Certiorari","Cert."],
 	["Compel", "Compel"],
 	["Complaint", "Compl."],
 	["Counterclaim", "Countercl."],
 	["Court", "Ct."],
 	["Cross-claim", "Cross-cl."],
 	["Declaration", "Decl."],
 	["Defendant [’s]", "Def. [’s]"],
 	["Defendants [’]", "Defs. [’]"],
 	["Demurrer", "Dem."],
 	["Deny [ing]", "Den."],
 	["Deposition","Dep."],
 	["Discovery", "Disc."],
 	["Dismiss", "Dismiss"],
 	["Docket","Docket"],
 	["Document", "Doc."],
 	["Evidence", 	"Evid."],
 	["Exhibit", "Ex."],
 	["Grant", "Grant"],
 	["Hearing", "Hr’g"],
 	["Injunction", "Inj."],
 	["Instruction","Instr."],
 	["Interrogatory", "Interrog."],
 	["Joint Appendix", "J.A."],
 	["Judgment", "J."],
 	["Limine","Lim."],
 	["Memorandum", "Mem."],
 	["Minute", "Min."],
 	["Motion", "Mot."],
 	["Objection","Obj."],
 	["Opinion", "Op."],
 	["Opposition", "Opp’n"],
 	["Order", "Order"],
 	["Petition", "Pet."],
 	["Petitioner [’s]", "Pet’r [’s]"],
 	["Petitioners [’]", "Pet’rs [’]"],
 	["Plaintiff [’s]", "Pl. [’s]"],
 	["Plaintiffs [’]", "Pls. [’]"],
 	["Points and Authorities", "P. & A."],
 	["Preliminary", "Prelim."],
 	["Produc [e, tion]", "Produc."],
 	["Quash", "Quash"],
 	["Reconsideration", "Recons."],
 	["Record", "R."],
 	["Rehearing", "Reh’g"],
 	["Reply", "Reply"],
 	["Report and Recommendation","R. & R."],
 	["Reporter", "Rep."],
 	["Request", "Req."],
 	["Respondent", "Resp’t"],
 	["Response", "Resp."],
 	["Stay","Stay"],
 	["Subpoena", "Subpoena"],
 	["Summary", "Summ."],
 	["Supplement [al]", "Suppl."],
 	["Support", "Supp."],
 	["Suppress", "Suppress"],
 	["Temporary Restraining Order", "TRO"],
 	["Testimony", "Test."],
 	["Transcript", "Tr."],
 	["Verified Statement", "V.S."],

]
